### ISSUE TITLE
Any solution ?

### ISSUE THREAD

**Issue by esutton** [andrewoverton/TestAccessoryManager#1]
iPad running iOS 10.0.2
Xcode 8.0

In Xcode debugger I see:
`Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement`

**Comment by andrewoverton** [comment]
Hi @esutton, we just added the following to our Info.plist and it worked:

```
<key>UIBackgroundModes</key>
<array>
    <string>external-accessory</string>
</array>
```

We weren't actually using the accessory in the background, but this was a suitable workaround for us. If you're having the same issue we did this should do it.

**Comment by esutton** [comment]
@andrewoverton Thank you.

I still get Xcode debug message:

`Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement`

However I can now see my External Accessory.

With this added capability I can even continue a software update of my accesssory when app is in the background. Very nice!

![screen shot 2016-10-06 at 12 04 47 pm](https://cloud.githubusercontent.com/assets/6115047/19162355/25293884-8bbd-11e6-9173-6e7a52c52b30.png)
